### ISSUE TITLE
sbin/solr.install tomcat-users.xml issue

### ISSUE THREAD

**Issue by ljackwilson** [dhinitiative/islandora#1]
These 3 lines:
`sed -i "s|</tomcat-users>|<!- for Solr ->|g" ${CATALINA_HOME}/conf/tomcat-users.xml`
`echo "<role rolename="solr_manager_role"/>" >> ${CATALINA_HOME}/conf/tomcat-users.xml`
`echo "<user username="$FEDORA_ADMIN_USER" password="$FEDORA_ADMIN_PASS" roles="solr_manager_role"/>" >> ${CATALINA_HOME}/conf/tomcat-users.xml`

should be:
`sed -i "s|</tomcat-users>|<!-- for Solr -->|g" ${CATALINA_HOME}/conf/tomcat-users.xml`
`echo "<role rolename=\"solr_manager_role\"/>" >> ${CATALINA_HOME}/conf/tomcat-users.xml`
`echo "<user username=\"$FEDORA_ADMIN_USER\" password=\"$FEDORA_ADMIN_PASS\" roles=\"solr_manager_role\"/>" >> ${CATALINA_HOME}/conf/tomcat-users.xml`

Which fixes two issues:
1. The "for Solr" comment line showed a dash and question mark, which caused tomcat to fail on a parse error on startup. Took a while to track down, since I could only see the ? when I copied the text from the file to another file. 
2. Tomcat also had trouble parsing the attribute values which weren't enclosed in quotation marks.

I made this one change and did a new test install, and this time all worked perfectly. Environment is Centos 6.7.

Thanks...jack

**Comment by hamhpc** [comment]
Awesome .. changes made!  Thanks a bunch for letting me know.
